[variables]
NODE_ENV = "production"
CI = "false"
GENERATE_SOURCEMAP = "false"
DISABLE_ESLINT_PLUGIN = "true"
NODE_OPTIONS = "--max-old-space-size=2048"

[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install --no-audit --no-fund',
  'cd frontend && npm install --no-audit --no-fund',
  'cd ../backend && npm install --no-audit --no-fund'
]

[phases.build]
cmds = [
  'cd frontend && CI=false GENERATE_SOURCEMAP=false DISABLE_ESLINT_PLUGIN=true npm run build'
]

[start]
cmd = 'npm start'
