[phases.setup]
nixPkgs = ['nodejs-18_x']

[phases.install]
cmds = [
  'npm install',
  'cd frontend && npm install',
  'cd ../backend && npm install'
]

[phases.build]
cmds = [
  'cd frontend && CI=false npm run build'
]

[start]
cmd = 'npm start'
