[build]
builder = "nixpacks"
buildCommand = "npm install && cd frontend && npm install && cd .. && cd backend && npm install && cd .. && cd frontend && CI=false npm run build"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
NODE_ENV = "production"
CI = "false"
